site_name: thunderlab

repo_url: https://github.com/bendalab/thunderlab/

edit_uri: ""

site_author: Benda-Lab

theme: readthedocs
    
nav:
    - Home: 'index.md'
    - 'User guide':
        - 'Multivariate explorer': 'multivariateexplorer.md'
    - 'Code':
        - API reference: 'api/index.html'
